backend:
  name: git-gateway
  branch: main

media_folder: "static/Images"
public_folder: "/Images"

locale: "pl"

collections:
  - name: "pages_pl"
    label: "Strony (PL)"
    folder: "content/pl"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Podtytuł", name: "subtitle", widget: "string", required: false}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Treść", name: "body", widget: "markdown"}

  - name: "services_pl"
    label: "Usługi (PL)"
    folder: "content/pl/uslugi"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Podtytuł", name: "subtitle", widget: "string", required: false}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Treść", name: "body", widget: "markdown"}

  - name: "pages_en"
    label: "Pages (EN)"
    folder: "content/en"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "services_en"
    label: "Services (EN)"
    folder: "content/en/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
